### ISSUE TITLE
Cancelled NavigateViewForResultAsync with Qualifiers.Dialog does not close the dialog

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno.extensions#1480] opened 2023-05-19 20:15 UTC
## Current behavior

This is how I open the dialog:
`await Navigator.NavigateViewForResultAsync<DisplayOffPage, bool>(this, qualifier: Qualifiers.Dialog, cancellation: cts.Token);`

And then at some external event I cancel the cts ('cts.Cancel();'). This will complete the `await showDialog.Result;` call, but the dialog is still on the screen and I have to click on it to get it to disappear.

## Expected behavior

The dialog should disappear from screen when cancellationTask is triggered.

## Environment

Tested on Skia.GTK

Nuget Package: Uno.Extensions 2.3.11

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [X] 2022 (version: 17.6)

**Comment by HakanL** [comment] 2023-05-19 20:37
Note that my dialog is a Page, not ContentDialog, not sure if that makes a difference.

**Comment by nickrandolph** [comment] 2023-05-24 05:55
I've added a sample of this to the test harness (https://github.com/unoplatform/uno.extensions/blob/36b85635ae6abacce56ff5d19a1aa21013a4f243/testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml.cs#L35-L37). Can you let me know if your code is different from this and/or provide a simple app that reproduces the issue

**Comment by HakanL** [comment] 2023-05-24 06:16
That matches my code, but I found out that for the cancel to work the dialog had to be of type ContentDialog. If it's of Page type (like my example was), then this issue appears. So in your test harness Widget has to be a Page (if this use case is supported).

**Comment by nickrandolph** [comment] 2023-06-07 05:07
Are you able to share your routemaps - In the example I quoted in the TestHarness the "DialogsBasic" maps to a view that is a page, so it should match what you're trying to do.
For information one of the differences is that by default a Page will open in a flyout, whereas for a type that derives from ContentDialog will be opened as a content dialog. Either way I'm interested to know what scenario it is that's not closing on cancellation.

**Comment by HakanL** [comment] 2023-06-07 05:11
I don't even have the Page-based dialog in the routemaps, but here they are:
```
        private static void RegisterRoutes(IViewRegistry views, IRouteRegistry routes)
        {
            views.Register(
                new ViewMap(ViewModel: typeof(ShellViewModel)),
                new ViewMap<HomePage, HomeViewModel>(),
                new ViewMap<MainPage, MainViewModel>(),
                new DataViewMap<AboutPage, AboutViewModel, Entity>()
            );

            routes.Register(
                new RouteMap("", View: views.FindByViewModel<ShellViewModel>(),
                    Nested: new RouteMap[]
                    {
                        new RouteMap("Home", View: views.FindByViewModel<HomeViewModel>()),
                        new RouteMap("Main", View: views.FindByViewModel<MainViewModel>()),
                        new RouteMap("About", View: views.FindByViewModel<AboutViewModel>()),
                    }
                )
            );
        }
```
I changed my dialog to use ContentDialog now so I don't have the set up that failed before. I wonder if it could be related to #1539 that is now working. The issue is that this issue was many revisions ago so I'm not sure I can easily set it up again.

**Comment by nickrandolph** [comment] 2023-06-07 05:18
So I don't see your content dialog includes in the routemap. It's worth including it to avoid the reflection overhead.

**Comment by nickrandolph** [comment] 2023-06-16 07:54
@HakanL are we ok to close this issue, since not able to reproduce it with latest release?

**Comment by HakanL** [comment] 2023-06-19 18:25
@nickrandolph I can still reproduce it (note that the issue is when I navigate to a `Page`, not a `ContentDialog`). Example is here: https://github.com/HakanL/Uno-Navigate-Issue (click the Display overlay button, the red overlay should disappear after 2 seconds).

**Comment by nickrandolph** [comment] 2023-06-19 18:44
Ok thanks. I will give it a go and try to fix tomorrow

**Comment by HakanL** [comment] 2023-06-19 18:50
Not urgent, since it works if I change it to a ContentDialog base class, but since I just want to display a clean (transparent) overlay, to prevent clicks when my backlight turns off, https://github.com/unoplatform/uno/discussions/10695), a Page base class would be good if it worked. I've hacked my ContentDialog page to work for the moment.

**Comment by nickrandolph** [comment] 2023-07-21 02:14
@HakanL can you verify that the latest version of extensions does close the flyout - I'll close this issue but if it's not working, comment here

**Closed by nickrandolph** 2023-07-21 02:14 UTC
Labels: kind/bug, triage/untriaged

**Comment by HakanL** [comment] 2023-07-21 03:41
@nickrandolph I've tested with extensions version 2.5.0-dev.167, but it's still not working. FWIW it's not actually a Flyout, but a regular page that I navigate to like a dialog:
```
var popupCancellationTokenSource = new CancellationTokenSource(2_000);

var result = await _navigator.NavigateViewForResultAsync<OverlayPage, bool>(this, qualifier: Qualifiers.Dialog, cancellation: popupCancellationTokenSource.Token);
```

**Comment by nickrandolph** [comment] 2023-07-21 03:53
And just to confirm, are you seeing this on all platforms?

**Comment by HakanL** [comment] 2023-07-21 03:57
> And just to confirm, are you seeing this on all platforms?

I'm primarily using Skia (on Win and LinuxFB), but I have a WinUI head as well. There is works differently, the cancel doesn't close the dialog page, but if I click on a different window (not inside my app, but like a browser, etc) then I notice that the dialog is closed. You should be able to run the repo I linked above to repro it.

**Comment by nickrandolph** [comment] 2023-07-21 05:17
I grabbed your repo and updated to latest dev version 3.0.0-dev.1984 (which also requires updating uno to v5) and the dialog closes after 2s

I did realise I didn't backport this fix - I've now done this, so it will be available on the 2.5-dev version once it merges (https://github.com/unoplatform/uno.extensions/pull/1676)

**Comment by HakanL** [comment] 2023-07-21 14:45
@nickrandolph Ah, I didn't realize you wanted me to test in 3.0, I thought 2.5 was the next version ;)
Perfect, thank you!

**Comment by nickrandolph** [comment] 2023-07-21 17:06
V3 is version compatible with v5 of Uno. 2.5 is next version compatible with 4.x of Uno
