### ISSUE TITLE
[Localization] Language changes won't apply 

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno.extensions#721] opened 2022-09-09 14:06 UTC
## Current behavior

After updating LocalizationSettings and restarting the app. Language change won't take effect.

## Expected behavior

Changeing LocalizationSettings and restarting the app should apply language changes.

## How to reproduce it (as minimally and precisely as possible)

-Open app
-Select Language
-Restart the app

Nuget Package: Uno.Extensions.Localization.WinUI

Package Version(s): 2.2.0-dev.244

Affected platform(s):

- [X] iOS
- [X] Android*
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

*On given repro works fine on Android, but using dev-225 it wasn't

Visual Studio:

- [X] 2022 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[TestApp1.zip](https://github.com/unoplatform/uno.extensions/files/9536061/TestApp1.zip)

**Comment by jeromelaban** [comment] 2022-09-15 17:11
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/6880

**Comment by nickrandolph** [comment] 2022-09-19 05:34
@jeromelaban I'm reopening this because it's not quite a duplicate. On iOS the Localization extension wasn't kicking in earlier enough at startup to set the localization.

**Closed** 2022-09-19 12:27 UTC
Labels: kind/bug, triage/untriaged
