### ISSUE TITLE
[MVUX] Make all feeds operators fluent friendly

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.extensions#2461] opened 2024-07-25 14:36 UTC
We should introduce a fluent builder pattern for creating/observing/manipulating Feeds/States on a model.

So Instead of needing to define the model and then subscribe to changes separately: 

```csharp  
public record MyModel
{

	public IFeed<Something> MyFeed => Feed.Async(.....);
	
	public MyModel()
	{
		MyFeed.ForEach(.....)
	}

}
```

We should have it all defined as part of a builder flow, something like:

```csharp  
public IFeed<Something> MyFeed => Feed.Async(.....).ForEach(.....);
```

We could even include add usage for subscribing to reactive messaging:

```csharp  
public record MyModel(IMessenger Messenger)
{
	public IFeed<Something> MyFeed => Feed
		.Async(.....)
		.ForEach(.....)
		.Observe(Messenger, something => something.Id);
}
```

Edit:
This is not only for `State.ForEachAsync` and `State.Observe` but we need to validate all operator

**Comment by kazo0** [comment] 2024-07-25 14:38
Will let @francoistanguay / @dr1rrb expand on the vision/thoughts here

**Comment by francoistanguay** [comment] 2024-08-13 17:27
Feed.ForEach exists? I thought it was just for IState.

.Observe is definitely for IState only, right?

**Comment by dr1rrb** [comment] 2024-08-13 18:10
This is a duplicate of https://github.com/unoplatform/uno.extensions/issues/2398 (it's not a "buidler pattern" but really about making operator "fluent friendly"... and in our case make sure to cache the result as we want to be able to use them as getter)



> Feed.ForEach exists? I thought it was just for IState.
> 
> .Observe is definitely for IState only, right?

Yes, both are for `IState`

**Comment by dr1rrb** [comment] 2024-08-13 18:13
Note: I'll close https://github.com/unoplatform/uno.extensions/issues/2398 in favor of this one as we have more discussion, but renaming this issue

**Comment by ajpinedam** [comment] 2024-08-19 16:43
Feed's current implementation uses a cache to hold the latest instance returned from the getter. This allows for better performance, but adding FluentAPI might have some performance implications, specifically on this caching part. Let's take, for example:

```csharp
public IFeed<Something> MyFeed => Feed
	.Async(.....)
	.ForEach(.....)
	.Observe(Messenger, something => something.Id);
```

If we make all of these operators `Async()`, `ForEach()`, and `Observe()` return the same Feed Instance, we would also need to ensure that our caching is updated on each iteration.

One way to minimize this performance implications would be by composing the Feeds using a Builder Pattern. The above could be replaced with something like 

```csharp
public IFeed<Something> MyFeed => Feed
        .Create( f =>
	    f.Async(.....)
  	    f.ForEach(.....)
	    f.Observe(Messenger, something => something.Id)
	);
```

or

```csharp
public IFeed<Something> MyFeed => Feed
        .Create()
	.Async(.....)
	.ForEach(.....)
	.Observe(Messenger, something => something.Id)
        .Build();
```

In terms of implementation, in the first approach, we introduce a new Operator, `Create` that takes in a function `Func<IFeedBuilder, IFeed>` where `IFeedBuilder` is an intermediate Feed object and `IFeed` is the resulting Feed that will be cached and returned in the Getter.

The second approach is a more typical implementation in which we have an operator `Builder()` or `Create() ', which returns the intermediate object `IFeedBuilder` that we use to create the final `IFeed.` Each operation acts over the same `IFeedBuilder` instance, and the final `Build` is responsible for making a concrete `IFeed` object that we cache and return from the Getter.

In either approach, the goal is to have a single entry in the Caching, which would be the returned value of the Builder operation.

Considerations:
Will we allow operations on the `IFeed` as we do now, or should all the operations be composed ONLY in the builder/Feed creation?

cc: @dr1rrb  @francoistanguay  @kazo0

**Comment by dr1rrb** [comment] 2024-08-20 18:13
Thinking about this, introducing a builder would also introduce a significant syntax update which is the opposite of what we did so far. It would also require a major effort to re-expose all operators on a builder object. Considering that a user typically have only few feeds per page, each having only a limited amount of operators, the perf impact introduced by caching each operator for fluent declaration is probably acceptable.

We should go with cached fluent operators and see if we notice a negative perf impact.

**Comment by francoistanguay** [comment] 2024-08-20 18:21
So please let's see the final proposed syntax (again, for State, not Feed).

**Comment by ajpinedam** [comment] 2024-08-21 00:06
For `State<T>`, we'll modify the following Operators, adding FluentAPI support.

`UpdateAsync()`
`ForEachAsync()` 
`SetAsync()`

This means we will be able to chain operators like:

State.Async().Observe().ForEach()

And the underlying IState object will be cached as we currently do.

We will also add a new Extension Method for the IState<T>. This will be the `Observe` Operator and it will have the following signature:

```
IState<TEntity> Observe<TEntity, TKey>(this IState<TEntity> state, IMessenger messenger, Func<TEntity, TKey> keySelector)
```

This extension method will be a wrapper around the Extension method that already exists for the `IMessenger`

cc: @dr1rrb @kazo0 @francoistanguay

**Comment by francoistanguay** [comment] 2024-08-21 00:20
I dont get why UpdateAsync and SetAsync should be fluent...

The whole idea is for State creation to be fluent so we can weave in Observe and ForEach...

**Comment by ajpinedam** [comment] 2024-08-21 00:45
Copied. Updating ForEach and adding Observe

**Comment by ajpinedam** [comment] 2024-08-21 00:59
@dr1rrb 

Should we consider renaming the `IState` operator `ForEachAsync()` to `ForEach` since the name implies it returns a Task or Async operation when, in fact, this is returning IDisposable and once we implement FluentAPI this one will return `IState<TEntity>`

**Comment by dr1rrb** [comment] 2024-08-27 07:22
> @dr1rrb
> 
> Should we consider renaming the `IState` operator `ForEachAsync()` to `ForEach` since the name implies it returns a Task or Async operation when, in fact, this is returning IDisposable and once we implement FluentAPI this one will return `IState<TEntity>`

Yes I think it makes sense 👍

**Closed** 2024-08-27 16:22 UTC
Labels: kind/enhancement
