### ISSUE TITLE
WPF fails to build due to CS0433 when MSAL is included

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.extensions#2004] opened 2023-09-12 09:05 UTC
## Current behavior

Trying to build 

## How to reproduce it (as minimally and precisely as possible)

- Run Wizard
- Select Blank template and Customize
- Add Skia WPF platform
- Add MSAL authentication
- Create
- Try to build the solution
- **Build fails with C:\Dev\Throwaway\UnoApp17\UnoApp17.Skia.WPF\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(13228,88,13228,100): error CS0433: The type 'CoreWebView2' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.864.35, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'**

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment] 2023-11-10 13:34
Closing as duplicate of https://github.com/unoplatform/uno.templates/issues/426 where not supported platforms are included by template

**Closed by nickrandolph** 2023-11-10 13:34 UTC
Labels: kind/bug, triage/untriaged
