### ISSUE TITLE
[Commerce App] Cart page missing "Your Cart" title and/or close icon button

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#195] opened 2021-12-02 18:30 UTC
**IMPORTANT: Please double-check the other platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

Cart page missing "Your Cart" title and/or close icon button
Can't navigate back on some platforms because of the missing close button
![image](https://user-images.githubusercontent.com/16295702/144481342-e86fa7d9-ee9c-4688-b10a-8638fcadf454.png)
![image](https://user-images.githubusercontent.com/16295702/144481397-d6fca858-399b-4e39-8771-1879f947a33e.png)
![image](https://user-images.githubusercontent.com/16295702/144481371-61aaa0cc-568a-4e25-a0b8-bcf7ce7f0b80.png)
[For Skia the close button icon seems different that we are supposed to have]

## Expected behavior

Cart page should have a "Your Cart" title and a close icon button on all platforms and look the same
Also we should be able to back from the page with the close button
![image](https://user-images.githubusercontent.com/16295702/144481879-815cec6f-fd7d-422d-abf8-b6e8a64413f5.png)

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Navigate to the Cart tab
- Notice the top of the CartPage

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] macOS
- [X] Skia
- [ ] Windows
- [ ] Build tasks

**Comment by Xiaoy312** [comment] 2021-12-02 18:37
did you test against the latest?
cause the [x] button should be showing now with: #190
if should be there, if you also see the "Your Cart" text (when NavBar itself is working, which on android it is completely broken)

**Comment by nickrandolph** [comment] 2021-12-17 08:11
@Xiaoy312 I'm seeing the X button across the platforms I've been testing (iOS, Android, Wasm, Windows). @agneszitte-nventive are you able to confirm this issue has been fixed?

**Comment by Xiaoy312** [comment] 2021-12-20 22:27
the [x] button issue should be fixed on all platforms
as for the navbar missing completely on mobile platforms,
- droid: working now
- ios: the navbar requires a `Frame` in order to properly render, which is missing from the current `main` branch (at 7563f852)

@nickrandolph i believe you have already started adding the frame in #228 
so, ill leave this to you to close it, since that is the only missing part.

**Comment by nickrandolph** [comment] 2021-12-21 00:15
@Xiaoy312 yep, my pr should include the frame/flyout fixes. It's just waiting on a review I think

**Comment by Xiaoy312** [comment] 2022-02-15 17:18
no longer reproducible on droid/ios/skia/wasm

**Closed by Xiaoy312** 2022-02-15 17:18 UTC
Labels: kind/bug, triage/untriaged
