### ISSUE TITLE
Enhance PlatformHelper class with a Platform enum property

### ISSUE THREAD

**Issue by BernhardPollerspoeck** [unoplatform/uno.extensions#1761] opened 2023-08-12 17:11 UTC
## What would you like to be added:
I want to add a Enum to PlatformHelper that indicates the current platform:

public enum EPlatform
{
    Undefined,

    Wpf,
    Wasm,
    Linux,
    Ios,
    Android,
}

In my own Implementation i at the moment set the 1 time setable property in the Program.cs(or compareable). This may should be moved to another location that is not dependant on the template.(There i might need some guidance)

## Why is this needed:
To be able to clearly identify the current platform

## For which Platform:

- [ x] iOS
- [ x] Android
- [ x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ x] Windows
- [ ] Build tasks

## Anything else we need to know?
I would do the implementation and prepase a PR.

**Comment by Youssef1313** [comment] 2023-08-14 05:48
This is a duplicate of https://github.com/unoplatform/uno/issues/11545.

I'll close as a duplicate, but I'm curious though about your exact use case.

**Closed by Youssef1313** 2023-08-14 05:48 UTC
Labels: kind/enhancement, triage/untriaged

**Comment by BernhardPollerspoeck** [comment] 2023-08-14 17:59
@Youssef1313 for me its as first usecase deciding navigation and displaying different pages based on platform.

i am going ahead and look into the linked issue and work out my questions there.
